name = "worker-links"
main = "src/index.ts"

# optional
#logpush = true

# Change these!!
kv_namespaces = [
  
  # Replace below line with your namespace ID ('yarn createkv' output) 
  { binding = "LINKS", id = "d9f9041dbf7740a9aaa5e779c4f38b06" }

  ]

compatibility_flags = []
compatibility_date = "2023-11-08"

# Remove or comment out the route line if using workers_dev (and set below to true)
workers_dev = false
route = { pattern = "southwell.app/*", zone_name = "southwell.app" }

[vars]
ENABLE_INDEX_FORM = true
